version: "3.7"

services:
  main:
    build:
      context: .
      target: runtime
    command: python python_project_template/__main__.py
    ports:
      - "8000:8000"
    profiles: ["main"]
    depends_on:
      - project-db

  project-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    profiles: ["project-db", "main"]
  
volumes:
  db-data: