site_name: ToolSense Flespi
nav:
  - Home: index.md
theme:
  name: material
  highlightjs: true
  highlightjs_style: monokai
  features:
    - content.code.copy
  palette:
    primary: 'orange'
  icon:
    repo: fontawesome/brands/github
repo_url: https://github.com/ToolSense/python-project-template
plugins:
  - git-revision-date-localized:
      enable_creation_date: true
  - tags
  - search
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      linenums: true
  - pymdownx.superfences
